# Generated by Django 6.0.2 on 2026-03-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proficiency', '0005_remove_proficiency_block_attacks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of the Map')),
                ('icon_name', models.CharField(default='unownmap_icon.png', max_length=29, verbose_name='Icon of the Map')),
                ('mode', models.CharField(choices=[('GG', 'Gem-Grab'), ('BW', 'Brawl-Ball'), ('BO', 'Bounty'), ('HE', 'Heist'), ('HZ', 'Hot-Zone'), ('KN', 'Knockout'), ('WO', 'Wipeout'), ('BH', 'Brawl-Hockey'), ('SW', 'Spirit-Wars'), ('PP', 'Present-Plunder'), ('BK', 'Basket-Brawl'), ('VY', 'Volley-Brawl'), ('PT', 'Paint-Brawl'), ('SC', 'Soul-Collector'), ('BA', 'Brawl-Arena'), ('TR', 'Token-Run'), ('TH', 'Treasure-Hunt'), ('DG', 'Dodgebrawl'), ('SB', 'Save-Blast')], max_length=2, verbose_name='Gamemode of the Map')),
                ('proficiency_multiplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proficiency.proficiency', verbose_name='The proficiencies of brawlers and others are multiplied from this map proficiencies, so use 10 by default and rarely use numbers above 25. All numbers here are divided by ten before being used as a multiplier')),
            ],
        ),
    ]
