# Generated by Django 6.0.2 on 2026-03-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('proficiency', '0005_remove_proficiency_block_attacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='proficiency_multiplier',
            field=models.ForeignKey(help_text='The proficiencies of brawlers and others are multiplied from this map proficiencies, so use 10 by default and rarely use numbers above 25. All numbers here are divided by ten before being used as a multiplier', on_delete=django.db.models.deletion.PROTECT, to='proficiency.proficiency', verbose_name='Proficiency Multiplier'),
        ),
    ]
