# Generated by Django 6.0.2 on 2026-03-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_map_proficiency_multiplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Map', 'verbose_name_plural': 'Maps'},
        ),
    ]
