from django.db import models

# Create your models here.
class Proficiency(models.Model):
    proficiency_id = models.IntegerField(primary_key=True)

    # Ataques: Dano e resistência
    durability = models.SmallIntegerField(verbose_name="Durability", help_text="capacidade de resistir a muitos ataques")
    counter_durability = models.SmallIntegerField(verbose_name="Counter Durability", help_text="capacidade de causar problemas para brawlers resistentes")
    attack_distance = models.SmallIntegerField(verbose_name="Attack-Distance", help_text="capacidade de causar danos em um alcance longo")
    counter_attack_distance = models.SmallIntegerField(verbose_name="Counter Attack-Distance", help_text="capacidade de evitar danos a um longo alcance")
    surprise_attack = models.SmallIntegerField(verbose_name="Surprise-Attack", help_text="capacidade de rushar em inimigos rapidamente")
    counter_surprise_attack = models.SmallIntegerField(verbose_name="Counter Surprise-Attack", help_text="capacidade de impedir Rushs de Assasinos")
    easy_approximation = models.SmallIntegerField(verbose_name="Easy-Approximation", help_text="capacidade de evitar ataques")
    counter_easy_approximation = models.SmallIntegerField(verbose_name="Counter Easy-Aproximation", help_text="capacidade de lidar com inimigos que evitam ataques com facilidade")
    burst_damage = models.SmallIntegerField(verbose_name="Burst-Damage", help_text="capacidade de aplicar descargas de dano massivo")
    counter_burst_damage = models.SmallIntegerField(verbose_name="Counter Burst-Damage", help_text="capacidade de resistir a descargas de dano massivo")
    objects_burst_damage = models.SmallIntegerField(verbose_name="Objects-Burst-Damage", help_text="capacidade de aplicar descargas de dano massivo em objetos que não se movem")
    counter_objects_burst_damage = models.SmallIntegerField(verbose_name="Counter Objects-Burst-Damage", help_text="Capacidade de resistir a descargas de dano massivo em objetos que não se movem")
    indirect_damage = models.SmallIntegerField(verbose_name="Indirect-Damage", help_text="capacidade de causar dano através de muros ou covers")
    counter_indirect_damage = models.SmallIntegerField(verbose_name="Counter Indirect-Damage", help_text="capacidade de evitar danos por detrás de muros e covers")
    area_denial = models.SmallIntegerField(verbose_name="Area-Denial", help_text="capacidade de impedir a passagem de inimigos por espaços")
    counter_area_denial = models.SmallIntegerField(verbose_name="Counter Area-Denial", help_text="capacidade de ignorar o impedimento de passagem por espaços")
    multiple_pets = models.SmallIntegerField(verbose_name="Multiple-Pets", help_text="capacidade de fazer pressão com o spawn de mais inimigos")
    counter_multiple_pets = models.SmallIntegerField(verbose_name="Counter Multiple-Pets", help_text="capacidade de lidar com a pressão de múltiplos inimigos em cena")
    durable_pets = models.SmallIntegerField(verbose_name="Durable-Pets", help_text="capacidade de gerar pets resistentes que forçam o gasto de recursos")
    counter_durable_pets = models.SmallIntegerField(verbose_name="Counter Durable-Pets", help_text="capacidade de lidar com a pressão de inimigos resistentes em cena sem gastar muitos recursos")
    turret_power = models.SmallIntegerField(verbose_name="Turret-Control", help_text="capacidade de gerar torretas que incomodam inimigos e são dificilmente destruíveis")
    counter_turret_power = models.SmallIntegerField(verbose_name="Counter Turret-Power", help_text="capacidade de destruir torretas que incomodam dos inimigos")
    wide_attack = models.SmallIntegerField(verbose_name="Wide-Attack", help_text="capacidade de atingir grandes áreas com seus ataques")
    counter_wide_attack = models.SmallIntegerField(verbose_name="Counter Wide-Attack", help_text="capacidade de enfrentar brawlers com áreas de ataque grandes")
    retreat_button = models.SmallIntegerField(verbose_name="Retreat-Button", help_text="capacidade de escapar de uma situação perigosa rapidamente")
    counter_retreat_button = models.SmallIntegerField(verbose_name="Counter Retreat-Button", help_text="capacidade de evitar problemas relacionados a fugas de inimigos")
    auto_fire_punishment = models.SmallIntegerField(verbose_name="Auto-Fire-Punishment", help_text="capacidade de manipular o auto-fire inimigo ao spawnar outras entidades, forçando a mira")
    counter_auto_fire_punishment = models.SmallIntegerField(verbose_name="Counter Auto-Fire-Punishment", help_text="capacidade de evitar problemas relacionados a manipulação de auto-fire")

    # Controle direto: Muros e Pressão
    open_lane_pressure = models.SmallIntegerField(verbose_name="Open-Lane-Pressure", help_text="capacidade de manter inimigos recuados em lanes abertas")
    counter_open_lane_pressure = models.SmallIntegerField(verbose_name="Counter Open-Lane-Pressure", help_text="capacidade de se aproximar perante pressão inimiga em lanes abertas")
    closed_lane_pressure = models.SmallIntegerField(verbose_name="Closed-Lane-Pressure", help_text="capacidade de manter inimigos recuados em lanes fechadas")
    counter_closed_lane_pressure = models.SmallIntegerField(verbose_name="Counter Closed-Lane-Pressure", help_text="capacidade de se aproximar perante pressão inimiga em lanes fechadas")
    grassy_lane_pressure = models.SmallIntegerField(verbose_name="Grassy-Lane-Pressure", help_text="capacidade de manter inimigos recuados em lanes com muita moita")
    counter_grassy_lane_pressure = models.SmallIntegerField(verbose_name="Counter Grassy-Lane-Pressure", help_text="capacidade de se aproximar perante pressão inimiga em lanes com muita moita")
    wall_break_efficiency = models.SmallIntegerField(verbose_name="Wall-Break-Efficiency", help_text="capacidade de destruição de muros")
    counter_wall_break_efficiency = models.SmallIntegerField(verbose_name="Counter Wall-Break-Efficiency", help_text="capacidade de evitar problemas mesmo em mapas sem muros")
    grass_break_efficiency = models.SmallIntegerField(verbose_name="Grass-Break-Efficiency", help_text="capacidade de destruição de moitas")
    counter_grass_break_efficiency = models.SmallIntegerField(verbose_name="Counter Grass-Break-Efficiency", help_text="capacidade de evitar problemas mesmo em mapas sem moitas")
    enemy_position_manipulation = models.SmallIntegerField(verbose_name="Enemy-Position-Manipulation", help_text="capacidade de manipular a posição de inimigos com puxões ou empurrões")
    counter_enemy_position_manipulation = models.SmallIntegerField(verbose_name="Counter Enemy-Position-Manipulation", help_text="capacidade de evitar problemas relacionados a puxões e empurrões de inimigos")
    groupment_punishment = models.SmallIntegerField(verbose_name="Groupment-Punishment", help_text="capacidade de punir inimigos próximos")
    counter_groupment_punishment = models.SmallIntegerField(verbose_name="Counter Groupment-Punishment", help_text="capacidade de evitar problemas relacionados ao agrupamento de aliados")
    water_walking = models.SmallIntegerField(verbose_name="Water-Walking", help_text="capacidade de andar sobre a água")
    counter_water_walking = models.SmallIntegerField(verbose_name="Counter Water-Walking", help_text="capacidade de enfrentar inimigos que andam sobre a água")

    # Buffs: Suporte e seus counters
    heal_buffing = models.SmallIntegerField(verbose_name="Heal-Buffing", help_text="capacidade de regenerar a vida de aliados")
    counter_heal_buffing = models.SmallIntegerField(verbose_name="Counter Heal-Buffing", help_text="capacidade de reduzir eficácia de regeneração de vida")
    shield_buffing = models.SmallIntegerField(verbose_name="Shield-Buffing", help_text="capacidade de aplicar escudos temporários a aliados")
    counter_shield_buffing = models.SmallIntegerField(verbose_name="Counter Shield-Buffing", help_text="capacidade de reduzir eficácia de escudos temporários")
    damage_buffing = models.SmallIntegerField(verbose_name="Damage-Buffing", help_text="capacidade de aumentar o dano causado por aliados")
    counter_damage_buffing = models.SmallIntegerField(verbose_name="Counter Damage-Buffing", help_text="capacidade de reduzir eficácia de buffs de dano")
    speed_buffing = models.SmallIntegerField(verbose_name="Speed-Buffing", help_text="capacidade de aplicar velocidade a aliados")
    counter_speed_buffing = models.SmallIntegerField(verbose_name="Counter Speed-Buffing", help_text="capacidade de reduzir eficácia de velocidade")
    invisibility_buffing = models.SmallIntegerField(verbose_name="Invisibility-Buffing", help_text="capacidade de aplicação de invisibilidade a aliados")
    counter_invisibility_buffing = models.SmallIntegerField(verbose_name="Counter Invisibility-Buffing", help_text="capacidade de evitar problemas relacionados a invisibilidade")
    positioning_buffing = models.SmallIntegerField(verbose_name="Positioning-Buffing", help_text="capacidade manipular a posição de aliados")
    counter_positioning_buffing = models.SmallIntegerField(verbose_name="Counter Positioning-Buffing", help_text="capacidade de reduzir eficácia de manipulação de posição de inimigos")
    poison_debuffing = models.SmallIntegerField(verbose_name="Poison-Debuffing", help_text="capacidade de aplicação de dano contínuo")
    counter_poison_debuffing = models.SmallIntegerField(verbose_name="Counter Poison-Debuffing", help_text="capacidade de reduzir eficácia de dano contínuo")
    stun_debuffing = models.SmallIntegerField(verbose_name="Stun-Debuffing", help_text="capacidade de aplicação de stun (paralisia)")
    counter_stun_debuffing = models.SmallIntegerField(verbose_name="Counter Stun-Debuffing", help_text="capacidade de reduzir eficácia de stun (paralisia)")
    slowness_debuffing = models.SmallIntegerField(verbose_name="Slowness-Debuffing", help_text="capacidade de aplicação de lentidão")
    counter_slowness_debuffing = models.SmallIntegerField(verbose_name="Counter Slowness-Debuffing", help_text="capacidade de reduzir eficácia de lentidão")
    block_attacks = models.SmallIntegerField(verbose_name="Block-Attacks", help_text="capacidade de anular ataques ou inimigos")
    counter_block_attacks = models.SmallIntegerField(verbose_name="Counter Block-Attacks", help_text="capacidade de reduzir eficácia de anulação de ataques ou inimigos")
    forced_stopped_time = models.SmallIntegerField(verbose_name="Forced-Stopped-Time", help_text="capacidade de dar um tempo antes de atacar ou executar uma ação poderosa, comum em ataques fortes")
    counter_forced_stopped_time = models.SmallIntegerField(verbose_name="Counter Forced-Stopped-Time", help_text="capacidade de cancelar ataques que demoram para acontecer")