from django.db import models

# Create your models here.
class Proficiency(models.Model):

    # Ataques: Dano e resistência
    durability = models.SmallIntegerField(verbose_name="Durability", help_text="capacidade de resistir a muitos ataques", default=0)
    counter_durability = models.SmallIntegerField(verbose_name="Counter Durability", help_text="capacidade de causar problemas para brawlers resistentes", default=0)
    attack_distance = models.SmallIntegerField(verbose_name="Attack-Distance", help_text="capacidade de causar danos em um alcance longo", default=0)
    counter_attack_distance = models.SmallIntegerField(verbose_name="Counter Attack-Distance", help_text="capacidade de evitar danos a um longo alcance", default=0)
    surprise_attack = models.SmallIntegerField(verbose_name="Surprise-Attack", help_text="capacidade de rushar em inimigos rapidamente", default=0)
    counter_surprise_attack = models.SmallIntegerField(verbose_name="Counter Surprise-Attack", help_text="capacidade de impedir Rushs de Assasinos", default=0)
    easy_approximation = models.SmallIntegerField(verbose_name="Easy-Approximation", help_text="capacidade de evitar ataques", default=0)
    counter_easy_approximation = models.SmallIntegerField(verbose_name="Counter Easy-Aproximation", help_text="capacidade de lidar com inimigos que evitam ataques com facilidade", default=0)
    burst_damage = models.SmallIntegerField(verbose_name="Burst-Damage", help_text="capacidade de aplicar descargas de dano massivo", default=0)
    counter_burst_damage = models.SmallIntegerField(verbose_name="Counter Burst-Damage", help_text="capacidade de resistir a descargas de dano massivo", default=0)
    objects_burst_damage = models.SmallIntegerField(verbose_name="Objects-Burst-Damage", help_text="capacidade de aplicar descargas de dano massivo em objetos que não se movem", default=0)
    counter_objects_burst_damage = models.SmallIntegerField(verbose_name="Counter Objects-Burst-Damage", help_text="Capacidade de resistir a descargas de dano massivo em objetos que não se movem", default=0)
    indirect_damage = models.SmallIntegerField(verbose_name="Indirect-Damage", help_text="capacidade de causar dano através de muros ou covers", default=0)
    counter_indirect_damage = models.SmallIntegerField(verbose_name="Counter Indirect-Damage", help_text="capacidade de evitar danos por detrás de muros e covers", default=0)
    area_denial = models.SmallIntegerField(verbose_name="Area-Denial", help_text="capacidade de impedir a passagem de inimigos por espaços", default=0)
    counter_area_denial = models.SmallIntegerField(verbose_name="Counter Area-Denial", help_text="capacidade de ignorar o impedimento de passagem por espaços", default=0)
    multiple_pets = models.SmallIntegerField(verbose_name="Multiple-Pets", help_text="capacidade de fazer pressão com o spawn de mais inimigos", default=0)
    counter_multiple_pets = models.SmallIntegerField(verbose_name="Counter Multiple-Pets", help_text="capacidade de lidar com a pressão de múltiplos inimigos em cena", default=0)
    durable_pets = models.SmallIntegerField(verbose_name="Durable-Pets", help_text="capacidade de gerar pets resistentes que forçam o gasto de recursos", default=0)
    counter_durable_pets = models.SmallIntegerField(verbose_name="Counter Durable-Pets", help_text="capacidade de lidar com a pressão de inimigos resistentes em cena sem gastar muitos recursos", default=0)
    turret_power = models.SmallIntegerField(verbose_name="Turret-Control", help_text="capacidade de gerar torretas que incomodam inimigos e são dificilmente destruíveis", default=0)
    counter_turret_power = models.SmallIntegerField(verbose_name="Counter Turret-Power", help_text="capacidade de destruir torretas que incomodam dos inimigos", default=0)
    wide_attack = models.SmallIntegerField(verbose_name="Wide-Attack", help_text="capacidade de atingir grandes áreas com seus ataques", default=0)
    counter_wide_attack = models.SmallIntegerField(verbose_name="Counter Wide-Attack", help_text="capacidade de enfrentar brawlers com áreas de ataque grandes", default=0)
    retreat_button = models.SmallIntegerField(verbose_name="Retreat-Button", help_text="capacidade de escapar de uma situação perigosa rapidamente", default=0)
    counter_retreat_button = models.SmallIntegerField(verbose_name="Counter Retreat-Button", help_text="capacidade de evitar problemas relacionados a fugas de inimigos", default=0)
    auto_fire_punishment = models.SmallIntegerField(verbose_name="Auto-Fire-Punishment", help_text="capacidade de manipular o auto-fire inimigo ao spawnar outras entidades, forçando a mira", default=0)
    counter_auto_fire_punishment = models.SmallIntegerField(verbose_name="Counter Auto-Fire-Punishment", help_text="capacidade de evitar problemas relacionados a manipulação de auto-fire", default=0)

    # Controle direto: Muros e Pressão
    open_lane_pressure = models.SmallIntegerField(verbose_name="Open-Lane-Pressure", help_text="capacidade de manter inimigos recuados em lanes abertas", default=0)
    counter_open_lane_pressure = models.SmallIntegerField(verbose_name="Counter Open-Lane-Pressure", help_text="capacidade de se aproximar perante pressão inimiga em lanes abertas", default=0)
    closed_lane_pressure = models.SmallIntegerField(verbose_name="Closed-Lane-Pressure", help_text="capacidade de manter inimigos recuados em lanes fechadas", default=0)
    counter_closed_lane_pressure = models.SmallIntegerField(verbose_name="Counter Closed-Lane-Pressure", help_text="capacidade de se aproximar perante pressão inimiga em lanes fechadas", default=0)
    grassy_lane_pressure = models.SmallIntegerField(verbose_name="Grassy-Lane-Pressure", help_text="capacidade de manter inimigos recuados em lanes com muita moita", default=0)
    counter_grassy_lane_pressure = models.SmallIntegerField(verbose_name="Counter Grassy-Lane-Pressure", help_text="capacidade de se aproximar perante pressão inimiga em lanes com muita moita", default=0)
    wall_break_efficiency = models.SmallIntegerField(verbose_name="Wall-Break-Efficiency", help_text="capacidade de destruição de muros", default=0)
    counter_wall_break_efficiency = models.SmallIntegerField(verbose_name="Counter Wall-Break-Efficiency", help_text="capacidade de evitar problemas mesmo em mapas sem muros", default=0)
    grass_break_efficiency = models.SmallIntegerField(verbose_name="Grass-Break-Efficiency", help_text="capacidade de destruição de moitas", default=0)
    counter_grass_break_efficiency = models.SmallIntegerField(verbose_name="Counter Grass-Break-Efficiency", help_text="capacidade de evitar problemas mesmo em mapas sem moitas", default=0)
    enemy_position_manipulation = models.SmallIntegerField(verbose_name="Enemy-Position-Manipulation", help_text="capacidade de manipular a posição de inimigos com puxões ou empurrões", default=0)
    counter_enemy_position_manipulation = models.SmallIntegerField(verbose_name="Counter Enemy-Position-Manipulation", help_text="capacidade de evitar problemas relacionados a puxões e empurrões de inimigos", default=0)
    groupment_punishment = models.SmallIntegerField(verbose_name="Groupment-Punishment", help_text="capacidade de punir inimigos próximos", default=0)
    counter_groupment_punishment = models.SmallIntegerField(verbose_name="Counter Groupment-Punishment", help_text="capacidade de evitar problemas relacionados ao agrupamento de aliados", default=0)
    water_walking = models.SmallIntegerField(verbose_name="Water-Walking", help_text="capacidade de andar sobre a água", default=0)
    counter_water_walking = models.SmallIntegerField(verbose_name="Counter Water-Walking", help_text="capacidade de enfrentar inimigos que andam sobre a água", default=0)

    # Buffs: Suporte e seus counters
    heal_buffing = models.SmallIntegerField(verbose_name="Heal-Buffing", help_text="capacidade de regenerar a vida de aliados", default=0)
    counter_heal_buffing = models.SmallIntegerField(verbose_name="Counter Heal-Buffing", help_text="capacidade de reduzir eficácia de regeneração de vida", default=0)
    shield_buffing = models.SmallIntegerField(verbose_name="Shield-Buffing", help_text="capacidade de aplicar escudos temporários a aliados", default=0)
    counter_shield_buffing = models.SmallIntegerField(verbose_name="Counter Shield-Buffing", help_text="capacidade de reduzir eficácia de escudos temporários", default=0)
    damage_buffing = models.SmallIntegerField(verbose_name="Damage-Buffing", help_text="capacidade de aumentar o dano causado por aliados", default=0)
    counter_damage_buffing = models.SmallIntegerField(verbose_name="Counter Damage-Buffing", help_text="capacidade de reduzir eficácia de buffs de dano", default=0)
    speed_buffing = models.SmallIntegerField(verbose_name="Speed-Buffing", help_text="capacidade de aplicar velocidade a aliados", default=0)
    counter_speed_buffing = models.SmallIntegerField(verbose_name="Counter Speed-Buffing", help_text="capacidade de reduzir eficácia de velocidade", default=0)
    invisibility_buffing = models.SmallIntegerField(verbose_name="Invisibility-Buffing", help_text="capacidade de aplicação de invisibilidade a aliados", default=0)
    counter_invisibility_buffing = models.SmallIntegerField(verbose_name="Counter Invisibility-Buffing", help_text="capacidade de evitar problemas relacionados a invisibilidade", default=0)
    positioning_buffing = models.SmallIntegerField(verbose_name="Positioning-Buffing", help_text="capacidade manipular a posição de aliados", default=0)
    counter_positioning_buffing = models.SmallIntegerField(verbose_name="Counter Positioning-Buffing", help_text="capacidade de reduzir eficácia de manipulação de posição de inimigos", default=0)
    poison_debuffing = models.SmallIntegerField(verbose_name="Poison-Debuffing", help_text="capacidade de aplicação de dano contínuo", default=0)
    counter_poison_debuffing = models.SmallIntegerField(verbose_name="Counter Poison-Debuffing", help_text="capacidade de reduzir eficácia de dano contínuo", default=0)
    stun_debuffing = models.SmallIntegerField(verbose_name="Stun-Debuffing", help_text="capacidade de aplicação de stun (paralisia)", default=0)
    counter_stun_debuffing = models.SmallIntegerField(verbose_name="Counter Stun-Debuffing", help_text="capacidade de reduzir eficácia de stun (paralisia)", default=0)
    slowness_debuffing = models.SmallIntegerField(verbose_name="Slowness-Debuffing", help_text="capacidade de aplicação de lentidão", default=0)
    counter_slowness_debuffing = models.SmallIntegerField(verbose_name="Counter Slowness-Debuffing", help_text="capacidade de reduzir eficácia de lentidão", default=0)
    block_attacks = models.SmallIntegerField(verbose_name="Block-Attacks", help_text="capacidade de anular ataques ou inimigos", default=0)
    counter_block_attacks = models.SmallIntegerField(verbose_name="Counter Block-Attacks", help_text="capacidade de reduzir eficácia de anulação de ataques ou inimigos", default=0)
    forced_stopped_time = models.SmallIntegerField(verbose_name="Forced-Stopped-Time", help_text="capacidade de dar um tempo antes de atacar ou executar uma ação poderosa, comum em ataques fortes", default=0)
    counter_forced_stopped_time = models.SmallIntegerField(verbose_name="Counter Forced-Stopped-Time", help_text="capacidade de cancelar ataques que demoram para acontecer", default=0)

    class Meta:
        verbose_name = "Proficiency"
        verbose_name_plural = "Proficiencies"