# Generated by Django 6.0.2 on 2026-02-17 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proficiency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Brawler Name')),
                ('primary_class', models.CharField(choices=[('D', 'Damage Dealer'), ('T', 'Tank'), ('AS', 'Assasin'), ('S', 'Support'), ('C', 'Controler'), ('M', 'Marksman'), ('AT', 'Artillery')], max_length=2, verbose_name='Primary Class')),
                ('secondary_class', models.CharField(choices=[('D', 'Damage Dealer'), ('T', 'Tank'), ('AS', 'Assasin'), ('S', 'Support'), ('C', 'Controler'), ('M', 'Marksman'), ('AT', 'Artillery')], max_length=2, verbose_name='Secondary Class')),
                ('base_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proficiency.proficiency', verbose_name='Base Proficiency')),
            ],
            options={
                'verbose_name': 'Brawler',
                'verbose_name_plural': 'Brawlers',
                'ordering': ['primary_class', 'secondary_class'],
            },
        ),
    ]
