# Generated by Django 6.0.2 on 2026-03-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='icon_name',
            field=models.CharField(default='unown_icon.png', max_length=34, verbose_name='Brawler Icon Name'),
        ),
    ]
