# Generated by Django 6.0.2 on 2026-03-09 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_power', '0003_alter_gadget_base_proficiency_and_more'),
        ('brawler', '0002_brawler_icon_name'),
        ('proficiency', '0008_remove_proficiency_counter_durability_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brawler',
            name='base_proficiency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proficiency.proficiency', verbose_name='Base Proficiency'),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='first_gadget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_gadget', to='additional_power.gadget', verbose_name='First Gadget'),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='first_starpower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_starpower', to='additional_power.starpower', verbose_name='First Star Power'),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='hipercharge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='additional_power.hipercharge', verbose_name='Hipercharge'),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='second_gadget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_gadget', to='additional_power.gadget', verbose_name='Second Gadget'),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='second_starpower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_starpower', to='additional_power.starpower', verbose_name='Second Star Power'),
        ),
    ]
