# Generated by Django 6.0.2 on 2026-06-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawler', '0003_alter_brawler_base_proficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='most_common_build',
            field=models.CharField(choices=[('00', 'Undefined Gadget, Undefined StarPower'), ('11', 'First Gadget, First StarPower'), ('12', 'First Gadget, Second StarPower'), ('21', 'Second Gadget, First StarPower'), ('22', 'Second Gadget, Second StarPower')], default='00', max_length=2, verbose_name='Most Common Build'),
        ),
    ]
