# Generated by Django 6.0.2 on 2026-02-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='area_denial',
            field=models.SmallIntegerField(default=0, help_text='capacidade de impedir a passagem de inimigos por espaços', verbose_name='Area-Denial'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='attack_distance',
            field=models.SmallIntegerField(default=0, help_text='capacidade de causar danos em um alcance longo', verbose_name='Attack-Distance'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='auto_fire_punishment',
            field=models.SmallIntegerField(default=0, help_text='capacidade de manipular o auto-fire inimigo ao spawnar outras entidades, forçando a mira', verbose_name='Auto-Fire-Punishment'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='block_attacks',
            field=models.SmallIntegerField(default=0, help_text='capacidade de anular ataques ou inimigos', verbose_name='Block-Attacks'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='burst_damage',
            field=models.SmallIntegerField(default=0, help_text='capacidade de aplicar descargas de dano massivo', verbose_name='Burst-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='closed_lane_pressure',
            field=models.SmallIntegerField(default=0, help_text='capacidade de manter inimigos recuados em lanes fechadas', verbose_name='Closed-Lane-Pressure'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_area_denial',
            field=models.SmallIntegerField(default=0, help_text='capacidade de ignorar o impedimento de passagem por espaços', verbose_name='Counter Area-Denial'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_attack_distance',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar danos a um longo alcance', verbose_name='Counter Attack-Distance'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_auto_fire_punishment',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar problemas relacionados a manipulação de auto-fire', verbose_name='Counter Auto-Fire-Punishment'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_block_attacks',
            field=models.SmallIntegerField(default=0, help_text='capacidade de reduzir eficácia de anulação de ataques ou inimigos', verbose_name='Counter Block-Attacks'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_burst_damage',
            field=models.SmallIntegerField(default=0, help_text='capacidade de resistir a descargas de dano massivo', verbose_name='Counter Burst-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_closed_lane_pressure',
            field=models.SmallIntegerField(default=0, help_text='capacidade de se aproximar perante pressão inimiga em lanes fechadas', verbose_name='Counter Closed-Lane-Pressure'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_damage_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de reduzir eficácia de buffs de dano', verbose_name='Counter Damage-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_durability',
            field=models.SmallIntegerField(default=0, help_text='capacidade de causar problemas para brawlers resistentes', verbose_name='Counter Durability'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_durable_pets',
            field=models.SmallIntegerField(default=0, help_text='capacidade de lidar com a pressão de inimigos resistentes em cena sem gastar muitos recursos', verbose_name='Counter Durable-Pets'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_easy_approximation',
            field=models.SmallIntegerField(default=0, help_text='capacidade de lidar com inimigos que evitam ataques com facilidade', verbose_name='Counter Easy-Aproximation'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_enemy_position_manipulation',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar problemas relacionados a puxões e empurrões de inimigos', verbose_name='Counter Enemy-Position-Manipulation'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_forced_stopped_time',
            field=models.SmallIntegerField(default=0, help_text='capacidade de cancelar ataques que demoram para acontecer', verbose_name='Counter Forced-Stopped-Time'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_grass_break_efficiency',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar problemas mesmo em mapas sem moitas', verbose_name='Counter Grass-Break-Efficiency'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_grassy_lane_pressure',
            field=models.SmallIntegerField(default=0, help_text='capacidade de se aproximar perante pressão inimiga em lanes com muita moita', verbose_name='Counter Grassy-Lane-Pressure'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_groupment_punishment',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar problemas relacionados ao agrupamento de aliados', verbose_name='Counter Groupment-Punishment'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_heal_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de reduzir eficácia de regeneração de vida', verbose_name='Counter Heal-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_indirect_damage',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar danos por detrás de muros e covers', verbose_name='Counter Indirect-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_invisibility_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar problemas relacionados a invisibilidade', verbose_name='Counter Invisibility-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_multiple_pets',
            field=models.SmallIntegerField(default=0, help_text='capacidade de lidar com a pressão de múltiplos inimigos em cena', verbose_name='Counter Multiple-Pets'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_objects_burst_damage',
            field=models.SmallIntegerField(default=0, help_text='Capacidade de resistir a descargas de dano massivo em objetos que não se movem', verbose_name='Counter Objects-Burst-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_open_lane_pressure',
            field=models.SmallIntegerField(default=0, help_text='capacidade de se aproximar perante pressão inimiga em lanes abertas', verbose_name='Counter Open-Lane-Pressure'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_poison_debuffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de reduzir eficácia de dano contínuo', verbose_name='Counter Poison-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_positioning_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de reduzir eficácia de manipulação de posição de inimigos', verbose_name='Counter Positioning-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_retreat_button',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar problemas relacionados a fugas de inimigos', verbose_name='Counter Retreat-Button'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_shield_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de reduzir eficácia de escudos temporários', verbose_name='Counter Shield-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_slowness_debuffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de reduzir eficácia de lentidão', verbose_name='Counter Slowness-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_speed_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de reduzir eficácia de velocidade', verbose_name='Counter Speed-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_stun_debuffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de reduzir eficácia de stun (paralisia)', verbose_name='Counter Stun-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_surprise_attack',
            field=models.SmallIntegerField(default=0, help_text='capacidade de impedir Rushs de Assasinos', verbose_name='Counter Surprise-Attack'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_turret_power',
            field=models.SmallIntegerField(default=0, help_text='capacidade de destruir torretas que incomodam dos inimigos', verbose_name='Counter Turret-Power'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_wall_break_efficiency',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar problemas mesmo em mapas sem muros', verbose_name='Counter Wall-Break-Efficiency'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_water_walking',
            field=models.SmallIntegerField(default=0, help_text='capacidade de enfrentar inimigos que andam sobre a água', verbose_name='Counter Water-Walking'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_wide_attack',
            field=models.SmallIntegerField(default=0, help_text='capacidade de enfrentar brawlers com áreas de ataque grandes', verbose_name='Counter Wide-Attack'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='damage_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de aumentar o dano causado por aliados', verbose_name='Damage-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='durability',
            field=models.SmallIntegerField(default=0, help_text='capacidade de resistir a muitos ataques', verbose_name='Durability'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='durable_pets',
            field=models.SmallIntegerField(default=0, help_text='capacidade de gerar pets resistentes que forçam o gasto de recursos', verbose_name='Durable-Pets'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='easy_approximation',
            field=models.SmallIntegerField(default=0, help_text='capacidade de evitar ataques', verbose_name='Easy-Approximation'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='enemy_position_manipulation',
            field=models.SmallIntegerField(default=0, help_text='capacidade de manipular a posição de inimigos com puxões ou empurrões', verbose_name='Enemy-Position-Manipulation'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='forced_stopped_time',
            field=models.SmallIntegerField(default=0, help_text='capacidade de dar um tempo antes de atacar ou executar uma ação poderosa, comum em ataques fortes', verbose_name='Forced-Stopped-Time'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='grass_break_efficiency',
            field=models.SmallIntegerField(default=0, help_text='capacidade de destruição de moitas', verbose_name='Grass-Break-Efficiency'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='grassy_lane_pressure',
            field=models.SmallIntegerField(default=0, help_text='capacidade de manter inimigos recuados em lanes com muita moita', verbose_name='Grassy-Lane-Pressure'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='groupment_punishment',
            field=models.SmallIntegerField(default=0, help_text='capacidade de punir inimigos próximos', verbose_name='Groupment-Punishment'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='heal_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de regenerar a vida de aliados', verbose_name='Heal-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='indirect_damage',
            field=models.SmallIntegerField(default=0, help_text='capacidade de causar dano através de muros ou covers', verbose_name='Indirect-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='invisibility_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de aplicação de invisibilidade a aliados', verbose_name='Invisibility-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='multiple_pets',
            field=models.SmallIntegerField(default=0, help_text='capacidade de fazer pressão com o spawn de mais inimigos', verbose_name='Multiple-Pets'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='objects_burst_damage',
            field=models.SmallIntegerField(default=0, help_text='capacidade de aplicar descargas de dano massivo em objetos que não se movem', verbose_name='Objects-Burst-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='open_lane_pressure',
            field=models.SmallIntegerField(default=0, help_text='capacidade de manter inimigos recuados em lanes abertas', verbose_name='Open-Lane-Pressure'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='poison_debuffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de aplicação de dano contínuo', verbose_name='Poison-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='positioning_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade manipular a posição de aliados', verbose_name='Positioning-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='retreat_button',
            field=models.SmallIntegerField(default=0, help_text='capacidade de escapar de uma situação perigosa rapidamente', verbose_name='Retreat-Button'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='shield_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de aplicar escudos temporários a aliados', verbose_name='Shield-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='slowness_debuffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de aplicação de lentidão', verbose_name='Slowness-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='speed_buffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de aplicar velocidade a aliados', verbose_name='Speed-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='stun_debuffing',
            field=models.SmallIntegerField(default=0, help_text='capacidade de aplicação de stun (paralisia)', verbose_name='Stun-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='surprise_attack',
            field=models.SmallIntegerField(default=0, help_text='capacidade de rushar em inimigos rapidamente', verbose_name='Surprise-Attack'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='turret_power',
            field=models.SmallIntegerField(default=0, help_text='capacidade de gerar torretas que incomodam inimigos e são dificilmente destruíveis', verbose_name='Turret-Control'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='wall_break_efficiency',
            field=models.SmallIntegerField(default=0, help_text='capacidade de destruição de muros', verbose_name='Wall-Break-Efficiency'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='water_walking',
            field=models.SmallIntegerField(default=0, help_text='capacidade de andar sobre a água', verbose_name='Water-Walking'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='wide_attack',
            field=models.SmallIntegerField(default=0, help_text='capacidade de atingir grandes áreas com seus ataques', verbose_name='Wide-Attack'),
        ),
    ]
