# Generated by Django 6.0.2 on 2026-02-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0002_alter_proficiency_area_denial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proficiency',
            name='auto_fire_punishment',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='closed_lane_pressure',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_auto_fire_punishment',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_closed_lane_pressure',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_grassy_lane_pressure',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_open_lane_pressure',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_turret_power',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='grassy_lane_pressure',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='open_lane_pressure',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='turret_power',
        ),
    ]
