# Generated by Django 6.0.2 on 2026-02-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0003_remove_proficiency_auto_fire_punishment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='area_denial',
            field=models.SmallIntegerField(default=0, help_text='Capacity of create effeck areas that block enemies (duration, area, effect)', verbose_name='Area-Denial'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='attack_distance',
            field=models.SmallIntegerField(default=0, help_text='Capacity of attack from long distances', verbose_name='Attack-Distance'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='burst_damage',
            field=models.SmallIntegerField(default=0, help_text='Capacity of dealing burst damage', verbose_name='Burst-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_area_denial',
            field=models.SmallIntegerField(default=0, help_text='(durability, (burst-damage, attack-distance), (surprise-attack, retreat-button))', verbose_name='Counter Area-Denial'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_attack_distance',
            field=models.SmallIntegerField(default=0, help_text='(attack-distance, surprise-attack, (durability, average-damage))', verbose_name='Counter Attack-Distance'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_burst_damage',
            field=models.SmallIntegerField(default=0, help_text='(retreat-button, (durability, easy-approximation))', verbose_name='Counter Burst-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_damage_buffing',
            field=models.SmallIntegerField(default=0, help_text='(duration, power)', verbose_name='Counter Damage-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_durability',
            field=models.SmallIntegerField(default=0, help_text='(average-damage, (attack-distance, durability))', verbose_name='Counter Durability'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_durable_pets',
            field=models.SmallIntegerField(default=0, help_text='(groupment-punishment, (burst-damage, wide-attack))', verbose_name='Counter Durable-Pets'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_easy_approximation',
            field=models.SmallIntegerField(default=0, help_text='(wide-attack, (burst-damage, durability))', verbose_name='Counter Easy-Aproximation'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_enemy_position_manipulation',
            field=models.SmallIntegerField(default=0, help_text='(durability, retreat-button, (burst-damage, enemy-position-manipulation))', verbose_name='Counter Enemy-Position-Manipulation'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_grass_break_efficiency',
            field=models.SmallIntegerField(default=0, help_text='Capacity of playing well after grass destruction', verbose_name='Counter Grass-Break-Efficiency'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_groupment_punishment',
            field=models.SmallIntegerField(default=0, help_text='(attack-distance, (10 - multiple-pets, 10 - durable-pets))', verbose_name='Counter Groupment-Punishment'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_heal_buffing',
            field=models.SmallIntegerField(default=0, help_text='(duration, power)', verbose_name='Counter Heal-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_indirect_damage',
            field=models.SmallIntegerField(default=0, help_text='(surprise-attack, (easy-approximation, velocity-buffing))', verbose_name='Counter Indirect-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_invisibility_buffing',
            field=models.SmallIntegerField(default=0, help_text='(wide-attack, attack-distance)', verbose_name='Counter Invisibility-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_multiple_pets',
            field=models.SmallIntegerField(default=0, help_text='(groupment-punishment, (wide-attack, (durable-pets, multiple-pets)))', verbose_name='Counter Multiple-Pets'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_objects_burst_damage',
            field=models.SmallIntegerField(default=0, help_text='(burst-damage, durability, attack-distance, surprise-attack)', verbose_name='Counter Objects-Burst-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_poison_debuffing',
            field=models.SmallIntegerField(default=0, help_text='(frequency, power)', verbose_name='Counter Poison-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_positioning_buffing',
            field=models.SmallIntegerField(default=0, help_text='(burst-damage, groupment-punishment)', verbose_name='Counter Positioning-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_retreat_button',
            field=models.SmallIntegerField(default=0, help_text='(easy-approximation, (collateral-effect, stun-capacity))', verbose_name='Counter Retreat-Button'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_shield_buffing',
            field=models.SmallIntegerField(default=0, help_text='(duration, power)', verbose_name='Counter Shield-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_slowness_debuffing',
            field=models.SmallIntegerField(default=0, help_text='(frequency, power)', verbose_name='Counter Slowness-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_speed_buffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of confront against speed enemies', verbose_name='Counter Speed-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_stun_debuffing',
            field=models.SmallIntegerField(default=0, help_text='(frequency, power)', verbose_name='Counter Stun-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_surprise_attack',
            field=models.SmallIntegerField(default=0, help_text='(durability, (burst-damage, potential-of-hitting-on-short-distance))', verbose_name='Counter Surprise-Attack'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_wall_break_efficiency',
            field=models.SmallIntegerField(default=0, help_text='Capacity of playing well after wall destruction', verbose_name='Counter Wall-Break-Efficiency'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_water_walking',
            field=models.SmallIntegerField(default=0, help_text='Capacity of dealing damage to water-walking enemies', verbose_name='Counter Water-Walking'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='counter_wide_attack',
            field=models.SmallIntegerField(default=0, help_text='(durability, (10 - multiple-pets, 10 - durable-pets))', verbose_name='Counter Wide-Attack'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='damage_buffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of increasing allies damage (frequency, power, duration)', verbose_name='Damage-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='durability',
            field=models.SmallIntegerField(default=0, help_text='Capacity of absorving damage', verbose_name='Durability'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='durable_pets',
            field=models.SmallIntegerField(default=0, help_text='Capacity of spawning durable pets/objects (frequency, (pet-durability, pet-damage, pet-velocity, pet-range))', verbose_name='Durable-Pets'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='easy_approximation',
            field=models.SmallIntegerField(default=0, help_text='Capacity of avoiding attacks and get closer (surprise-attack, (movement-speed, durability))', verbose_name='Easy-Approximation'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='enemy_position_manipulation',
            field=models.SmallIntegerField(default=0, help_text='Capacity of manipulating enemies position with attacks', verbose_name='Enemy-Position-Manipulation'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='grass_break_efficiency',
            field=models.SmallIntegerField(default=0, help_text='Capacity of grass destruction', verbose_name='Grass-Break-Efficiency'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='groupment_punishment',
            field=models.SmallIntegerField(default=0, help_text='Capacity of punishing enemies with other hitboxes around', verbose_name='Groupment-Punishment'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='heal_buffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of heal allies (frequency, power)', verbose_name='Heal-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='indirect_damage',
            field=models.SmallIntegerField(default=0, help_text='Capacity of dealing damage ignoring walls (frequency, (attack-distance, burst-damage))', verbose_name='Indirect-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='invisibility_buffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of applying invisibility on allies (frequency, duration)', verbose_name='Invisibility-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='multiple_pets',
            field=models.SmallIntegerField(default=0, help_text='Capacity of spawning multiple pets/objects (frequency, quantity)', verbose_name='Multiple-Pets'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='objects_burst_damage',
            field=models.SmallIntegerField(default=0, help_text='Capacity of dealing burst damage to non-players enemies (object-burst-damage, average-attack-distance)', verbose_name='Objects-Burst-Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='poison_debuffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of dealing continuous damage to enemies', verbose_name='Poison-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='positioning_buffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of increasing allies positioning (no parameters at this moment)', verbose_name='Positioning-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='retreat_button',
            field=models.SmallIntegerField(default=0, help_text='Capacity of escape from dangerous attacks (frequency, (versatility, power))', verbose_name='Retreat-Button'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='shield_buffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of summon shields on allies (frequency, power)', verbose_name='Shield-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='slowness_debuffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of decreasing enemies speed (frequency, power, duration)', verbose_name='Slowness-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='speed_buffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of increasing allies speed (frequency, duration)', verbose_name='Speed-Buffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='stun_debuffing',
            field=models.SmallIntegerField(default=0, help_text='Capacity of stun enemies', verbose_name='Stun-Debuffing'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='surprise_attack',
            field=models.SmallIntegerField(default=0, help_text='Capacity of rushing enemies quickly (frequency, (surprise-attack-distance, velocity))', verbose_name='Surprise-Attack'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='wall_break_efficiency',
            field=models.SmallIntegerField(default=0, help_text='Capacity of wall destruction', verbose_name='Wall-Break-Efficiency'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='water_walking',
            field=models.SmallIntegerField(default=0, help_text='Capacity of walking on water', verbose_name='Water-Walking'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='wide_attack',
            field=models.SmallIntegerField(default=0, help_text='Capacity of covering big areas with attacks', verbose_name='Wide-Attack'),
        ),
    ]
