# Generated by Django 6.0.2 on 2026-02-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0004_alter_proficiency_area_denial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proficiency',
            name='block_attacks',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_block_attacks',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_forced_stopped_time',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='forced_stopped_time',
        ),
        migrations.AddField(
            model_name='proficiency',
            name='attacks_canceling',
            field=models.SmallIntegerField(default=0, help_text='Capacity of cancel delayed attacks', verbose_name='Forced-Stopped-Time'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='block_enemies',
            field=models.SmallIntegerField(default=0, help_text='Capacity of neutralizing enemies (no parameters at this moment)', verbose_name='Block-Attacks'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='counter_attacks_canceling',
            field=models.SmallIntegerField(default=0, help_text='Capacity of not being affected by attacks canceling', verbose_name='Counter Forced-Stopped-Time'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='counter_block_enemies',
            field=models.SmallIntegerField(default=0, help_text='Capacity of not being neutralized (no parameters at this moment)', verbose_name='Counter Block-Attacks'),
        ),
    ]
