# Generated by Django 6.0.2 on 2026-03-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0005_remove_proficiency_block_attacks_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('durability__gte', 0)), name='durability_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_durability__gte', 0)), name='counter_durability_gte_0'),
        ),
    ]
