# Generated by Django 6.0.2 on 2026-03-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0006_proficiency_durability_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='durability_gte_0',
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('durability__gte', 0)), name='durability_greater_or_equal_to_0'),
        ),
    ]
