# Generated by Django 6.0.2 on 2026-03-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0007_remove_proficiency_durability_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_durability_gte_0',
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_durability__gte', 0)), name='counter_durability_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('attack_distance__gte', 0)), name='attack_distance_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_attack_distance__gte', 0)), name='counter_attack_distance_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('surprise_attack__gte', 0)), name='surprise_attack_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_surprise_attack__gte', 0)), name='counter_surprise_attack_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('easy_approximation__gte', 0)), name='easy_approximation_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_easy_approximation__gte', 0)), name='counter_easy_approximation_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('burst_damage__gte', 0)), name='burst_damage_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_burst_damage__gte', 0)), name='counter_burst_damage_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('objects_burst_damage__gte', 0)), name='objects_burst_damage_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_objects_burst_damage__gte', 0)), name='counter_objects_burst_damage_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('indirect_damage__gte', 0)), name='indirect_damage_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_indirect_damage__gte', 0)), name='counter_indirect_damage_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('area_denial__gte', 0)), name='area_denial_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_area_denial__gte', 0)), name='counter_area_denial_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('multiple_pets__gte', 0)), name='multiple_pets_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_multiple_pets__gte', 0)), name='counter_multiple_pets_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('durable_pets__gte', 0)), name='durable_pets_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_durable_pets__gte', 0)), name='counter_durable_pets_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('wide_attack__gte', 0)), name='wide_attack_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_wide_attack__gte', 0)), name='counter_wide_attack_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('retreat_button__gte', 0)), name='retreat_button_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_retreat_button__gte', 0)), name='counter_retreat_button_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('wall_break_efficiency__gte', 0)), name='wall_break_efficiency_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_wall_break_efficiency__gte', 0)), name='counter_wall_break_efficiency_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('grass_break_efficiency__gte', 0)), name='grass_break_efficiency_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_grass_break_efficiency__gte', 0)), name='counter_grass_break_efficiency_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('enemy_position_manipulation__gte', 0)), name='enemy_position_manipulation_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_enemy_position_manipulation__gte', 0)), name='counter_enemy_position_manipulation_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('groupment_punishment__gte', 0)), name='groupment_punishment_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_groupment_punishment__gte', 0)), name='counter_groupment_punishment_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('water_walking__gte', 0)), name='water_walking_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_water_walking__gte', 0)), name='counter_water_walking_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('heal_buffing__gte', 0)), name='heal_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_heal_buffing__gte', 0)), name='counter_heal_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('shield_buffing__gte', 0)), name='shield_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_shield_buffing__gte', 0)), name='counter_shield_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('damage_buffing__gte', 0)), name='damage_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_damage_buffing__gte', 0)), name='counter_damage_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('speed_buffing__gte', 0)), name='speed_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_speed_buffing__gte', 0)), name='counter_speed_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('invisibility_buffing__gte', 0)), name='invisibility_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_invisibility_buffing__gte', 0)), name='counter_invisibility_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('positioning_buffing__gte', 0)), name='positioning_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_positioning_buffing__gte', 0)), name='counter_positioning_buffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('poison_debuffing__gte', 0)), name='poison_debuffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_poison_debuffing__gte', 0)), name='counter_poison_debuffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('stun_debuffing__gte', 0)), name='stun_debuffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_stun_debuffing__gte', 0)), name='counter_stun_debuffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('slowness_debuffing__gte', 0)), name='slowness_debuffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_slowness_debuffing__gte', 0)), name='counter_slowness_debuffing_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('block_enemies__gte', 0)), name='block_enemies_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_block_enemies__gte', 0)), name='counter_block_enemies_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('attacks_canceling__gte', 0)), name='attacks_canceling_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('counter_attacks_canceling__gte', 0)), name='counter_attacks_canceling_greater_or_equal_to_0'),
        ),
    ]
