# Generated by Django 6.0.2 on 2026-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0008_remove_proficiency_counter_durability_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_durability_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_attack_distance_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_surprise_attack_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='easy_approximation_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_easy_approximation_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='burst_damage_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_burst_damage_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='objects_burst_damage_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_objects_burst_damage_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='indirect_damage_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_indirect_damage_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_area_denial_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='multiple_pets_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_multiple_pets_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='durable_pets_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_durable_pets_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_wide_attack_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_retreat_button_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_wall_break_efficiency_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_grass_break_efficiency_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_enemy_position_manipulation_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_groupment_punishment_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_shield_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_speed_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_invisibility_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_positioning_buffing_greater_or_equal_to_0',
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_accumulation_of_pets',
            field=models.SmallIntegerField(default=0, help_text='Capacity of keeping pets/objects on the field', verbose_name='Accumulation of Pets'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_deteriorability_of_pets',
            field=models.SmallIntegerField(default=0, help_text='Capacity of pets/objects to be destroyed by enemies', verbose_name='Deteriorability of Pets'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_frequency_of_pets_generation',
            field=models.SmallIntegerField(default=0, help_text='Capacity of generating pets/objects', verbose_name='Frequency of Pet Generation'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_indirect_damage_efficiency',
            field=models.SmallIntegerField(default=0, help_text='Frequency of indirect damage', verbose_name='Indirect-Damage-Efficiency'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_movement_speed',
            field=models.SmallIntegerField(default=0, help_text='Capacity of moving fast', verbose_name='Movement-Speed'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_pets_damage',
            field=models.SmallIntegerField(default=0, help_text='Capacity of pets/objects to deal damage to enemies', verbose_name='Pets Damage'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_pets_proximity',
            field=models.SmallIntegerField(default=0, help_text='Capacity of pets/objects to be close to allies, helping them to approach enemies', verbose_name='Pets Proximity'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_pets_range',
            field=models.SmallIntegerField(default=0, help_text='Capacity of pets/objects to reach enemies', verbose_name='Pets Range'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_pets_resistence',
            field=models.SmallIntegerField(default=0, help_text='Capacity of pets/objects to resist attacks', verbose_name='Pets Resistência'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_pets_speed',
            field=models.SmallIntegerField(default=0, help_text='Capacity of pets/objects to reach enemies quickly', verbose_name='Pets Speed'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_surprise_attack_power',
            field=models.SmallIntegerField(default=0, help_text='Capacity of dealing more damage on surprise attacks', verbose_name='Surprise-Attack-Power'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_indirect_damage_efficiency__gte', 0)), name='indirect_damage_efficiency_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_movement_speed__gte', 0)), name='movement_speed_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_surprise_attack_power__gte', 0)), name='surprise_attack_power_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_frequency_of_pets_generation__gte', 0)), name='frequency_of_pets_generation_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_accumulation_of_pets__gte', 0)), name='accumulation_of_pets_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_deteriorability_of_pets__gte', 0)), name='deteriorability_of_pets_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_pets_resistence__gte', 0)), name='pets_resistence_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_pets_damage__gte', 0)), name='pets_damage_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_pets_range__gte', 0)), name='pets_range_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_pets_speed__gte', 0)), name='pets_speed_greater_or_equal_to_0'),
        ),
        migrations.AddConstraint(
            model_name='proficiency',
            constraint=models.CheckConstraint(condition=models.Q(('_pets_proximity__gte', 0)), name='pets_proximity_greater_or_equal_to_0'),
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='burst_damage',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_area_denial',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_attack_distance',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_burst_damage',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_durability',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_durable_pets',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_easy_approximation',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_enemy_position_manipulation',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_grass_break_efficiency',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_groupment_punishment',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_indirect_damage',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_invisibility_buffing',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_multiple_pets',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_objects_burst_damage',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_positioning_buffing',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_retreat_button',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_shield_buffing',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_speed_buffing',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_surprise_attack',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_wall_break_efficiency',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_wide_attack',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='durable_pets',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='easy_approximation',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='indirect_damage',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='multiple_pets',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='objects_burst_damage',
        ),
    ]
