# Generated by Django 6.0.2 on 2026-05-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0009_remove_proficiency_counter_durability_greater_or_equal_to_0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='durability_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='attack_distance_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='surprise_attack_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='area_denial_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='wide_attack_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='retreat_button_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='wall_break_efficiency_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='grass_break_efficiency_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='enemy_position_manipulation_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='groupment_punishment_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='water_walking_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_water_walking_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='heal_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_heal_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='shield_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='damage_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_damage_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='speed_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='invisibility_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='positioning_buffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='poison_debuffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_poison_debuffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='stun_debuffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_stun_debuffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='slowness_debuffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_slowness_debuffing_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='block_enemies_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_block_enemies_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='attacks_canceling_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='counter_attacks_canceling_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='indirect_damage_efficiency_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='movement_speed_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='surprise_attack_power_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='frequency_of_pets_generation_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='accumulation_of_pets_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='deteriorability_of_pets_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='pets_resistence_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='pets_damage_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='pets_range_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='pets_speed_greater_or_equal_to_0',
        ),
        migrations.RemoveConstraint(
            model_name='proficiency',
            name='pets_proximity_greater_or_equal_to_0',
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_auto_charge_super',
            field=models.SmallIntegerField(default=0, help_text='Capacity of charging super without firing projectiles (frequency, power)', verbose_name='Auto-Charge Super'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_necessary_projectiles_to_charge_super',
            field=models.SmallIntegerField(default=0, help_text='Number of projectiles necessary to charge super', verbose_name='Necessary Projectiles to Charge Super'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_necessary_supers_to_charge_hipercharge',
            field=models.SmallIntegerField(default=0, help_text='Number of supers necessary to charge hipercharge', verbose_name='Necessary Supers to Charge Hipercharge'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_projectile_damage',
            field=models.SmallIntegerField(default=0, help_text='Damage of each projectile', verbose_name='Projectile Damage'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_shots_per_five_seconds',
            field=models.SmallIntegerField(default=0, help_text='Number of shots that can be fired in 5 seconds', verbose_name='Shots per 5 seconds'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='average_projectiles_per_shot',
            field=models.SmallIntegerField(default=0, help_text='Average number of projectiles fired in each shot', verbose_name='Average Projectiles per Shot'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='average_super_damage',
            field=models.SmallIntegerField(default=0, help_text='Average damage of super', verbose_name='Average Super Damage'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='circumstantiality_of_overall_proficiency',
            field=models.SmallIntegerField(default=0, help_text='Defines in what level this proficiency is dependent of external factors that need humam avaliation/observation', verbose_name='Circumstantiality of Overall Proficiency'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='cover_creation_efficiency',
            field=models.SmallIntegerField(default=0, help_text='Capacity of creating covers with attacks (duration, area, durability)', verbose_name='Cover-Creation-Efficiency'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='ocasional_extra_damage',
            field=models.SmallIntegerField(default=0, help_text='Capacity of dealing damage with ocasional attacks (frequency, power)', verbose_name='Ocasional Extra Damage'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='projectiles_per_shot_in_long_range',
            field=models.SmallIntegerField(default=0, help_text='Average number of projectiles fired in each shot when the enemy is far', verbose_name='Projectiles per Shot in Long Range'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='projectiles_per_shot_in_medium_range',
            field=models.SmallIntegerField(default=0, help_text='Average number of projectiles fired in each shot when the enemy is at medium distance', verbose_name='Projectiles per Shot in Medium Range'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='projectiles_per_shot_in_short_range',
            field=models.SmallIntegerField(default=0, help_text='Average number of projectiles fired in each shot when the enemy is close', verbose_name='Projectiles per Shot in Short Range'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='projectiles_per_shot_in_very_long_range',
            field=models.SmallIntegerField(default=0, help_text='Average number of projectiles fired in each shot when the enemy is very far', verbose_name='Projectiles per Shot in Very Long Range'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='super_damage_in_long_range',
            field=models.SmallIntegerField(default=0, help_text='Damage of super when the enemy is far', verbose_name='Super Damage in Long Range'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='super_damage_in_medium_range',
            field=models.SmallIntegerField(default=0, help_text='Damage of super when the enemy is at medium distance', verbose_name='Super Damage in Medium Range'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='super_damage_in_short_range',
            field=models.SmallIntegerField(default=0, help_text='Damage of super when the enemy is close', verbose_name='Super Damage in Short Range'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='super_damage_in_very_long_range',
            field=models.SmallIntegerField(default=0, help_text='Damage of super when the enemy is very far', verbose_name='Super Damage in Very Long Range'),
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='counter_block_enemies',
        ),
    ]
