# Generated by Django 6.0.2 on 2026-05-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0010_remove_proficiency_durability_greater_or_equal_to_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='_projectile_damage',
            field=models.IntegerField(default=0, help_text='Damage of each projectile', verbose_name='Projectile Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='average_super_damage',
            field=models.IntegerField(default=0, help_text='Average damage of super', verbose_name='Average Super Damage'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='super_damage_in_long_range',
            field=models.IntegerField(default=0, help_text='Damage of super when the enemy is far', verbose_name='Super Damage in Long Range'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='super_damage_in_medium_range',
            field=models.IntegerField(default=0, help_text='Damage of super when the enemy is at medium distance', verbose_name='Super Damage in Medium Range'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='super_damage_in_short_range',
            field=models.IntegerField(default=0, help_text='Damage of super when the enemy is close', verbose_name='Super Damage in Short Range'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='super_damage_in_very_long_range',
            field=models.IntegerField(default=0, help_text='Damage of super when the enemy is very far', verbose_name='Super Damage in Very Long Range'),
        ),
    ]
