# Generated by Django 6.0.2 on 2026-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0011_alter_proficiency__projectile_damage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proficiency',
            name='ocasional_extra_damage',
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_grass_vision',
            field=models.SmallIntegerField(default=0, help_text='Capacity of seeing enemies hiding in the grass', verbose_name='Grass-Vision'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='ocasional_damage',
            field=models.IntegerField(default=0, help_text='Capacity of dealing damage with ocasional attacks (frequency, power)', verbose_name='Ocasional Damage'),
        ),
    ]
