# Generated by Django 6.0.2 on 2026-05-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0012_remove_proficiency_ocasional_extra_damage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proficiency',
            old_name='groupment_punishment',
            new_name='_increased_damage_when_grouped',
        ),
    ]
