# Generated by Django 6.0.2 on 2026-05-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0013_rename_groupment_punishment_proficiency__increased_damage_when_grouped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proficiency',
            old_name='_grass_vision',
            new_name='grass_vision',
        ),
    ]
