# Generated by Django 6.0.2 on 2026-06-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0014_rename__grass_vision_proficiency_grass_vision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proficiency',
            old_name='attack_distance',
            new_name='_attack_distance',
        ),
        migrations.RenameField(
            model_name='proficiency',
            old_name='average_projectiles_per_shot',
            new_name='_average_projectiles_per_shot',
        ),
        migrations.RenameField(
            model_name='proficiency',
            old_name='durability',
            new_name='_durability',
        ),
        migrations.RenameField(
            model_name='proficiency',
            old_name='projectiles_per_shot_in_long_range',
            new_name='_projectiles_per_shot_in_long_range',
        ),
        migrations.RenameField(
            model_name='proficiency',
            old_name='projectiles_per_shot_in_medium_range',
            new_name='_projectiles_per_shot_in_medium_range',
        ),
        migrations.RenameField(
            model_name='proficiency',
            old_name='projectiles_per_shot_in_short_range',
            new_name='_projectiles_per_shot_in_short_range',
        ),
        migrations.RenameField(
            model_name='proficiency',
            old_name='projectiles_per_shot_in_very_long_range',
            new_name='_projectiles_per_shot_in_very_long_range',
        ),
        migrations.RenameField(
            model_name='proficiency',
            old_name='surprise_attack',
            new_name='_surprise_attack',
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_shotting_time',
            field=models.SmallIntegerField(default=0, help_text='Time necessary to be able to shoot again', verbose_name='Reshotting Time'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='_super_time',
            field=models.SmallIntegerField(default=0, help_text='Time necessary to be able to super again', verbose_name='Resuper Time'),
        ),
    ]
