# Generated by Django 6.0.2 on 2026-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0017_remove_proficiency_main_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiency',
            name='explanation_for_circumstantiality',
            field=models.CharField(default='none', verbose_name='Explanation for Circumstantiality'),
        ),
    ]
