# Generated by Django 6.0.2 on 2026-06-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiency', '0018_proficiency_explanation_for_circumstantiality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='explanation_for_circumstantiality',
            field=models.CharField(default='none', help_text='Explanation for the circumstantiality above (will be shown directly to the user)', verbose_name='Explanation for Circumstantiality'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='main_specific_weakness',
            field=models.CharField(choices=[('super_damage_in_short_range', 'super_damage_in_short_range'), ('super_damage_in_medium_range', 'super_damage_in_medium_range'), ('super_damage_in_long_range', 'super_damage_in_long_range'), ('super_damage_in_very_long_range', 'super_damage_in_very_long_range'), ('average_super_damage', 'average_super_damage'), ('ocasional_damage', 'ocasional_damage'), ('retreat_button', 'retreat_button'), ('wide_attack', 'wide_attack'), ('area_denial', 'area_denial'), ('enemy_position_manipulation', 'enemy_position_manipulation'), ('water_walking', 'water_walking'), ('counter_water_walking', 'counter_water_walking'), ('wall_break_efficiency', 'wall_break_efficiency'), ('grass_break_efficiency', 'grass_break_efficiency'), ('cover_creation_efficiency', 'cover_creation_efficiency'), ('grass_vision', 'grass_vision'), ('circumstantiality_of_overall_proficiency', 'circumstantiality_of_overall_proficiency'), ('heal_buffing', 'heal_buffing'), ('counter_heal_buffing', 'counter_heal_buffing'), ('shield_buffing', 'shield_buffing'), ('damage_buffing', 'damage_buffing'), ('counter_damage_buffing', 'counter_damage_buffing'), ('speed_buffing', 'speed_buffing'), ('invisibility_buffing', 'invisibility_buffing'), ('positioning_buffing', 'positioning_buffing'), ('poison_debuffing', 'poison_debuffing'), ('counter_poison_debuffing', 'counter_poison_debuffing'), ('stun_debuffing', 'stun_debuffing'), ('counter_stun_debuffing', 'counter_stun_debuffing'), ('slowness_debuffing', 'slowness_debuffing'), ('counter_slowness_debuffing', 'counter_slowness_debuffing'), ('block_enemies', 'block_enemies'), ('attacks_canceling', 'attacks_canceling'), ('counter_attacks_canceling', 'counter_attacks_canceling'), ('none', 'none')], default='none', help_text='Striking incapacity that could not be described until now', verbose_name='Main Specific Weakness'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='specific_weakness',
            field=models.CharField(choices=[('super_damage_in_short_range', 'super_damage_in_short_range'), ('super_damage_in_medium_range', 'super_damage_in_medium_range'), ('super_damage_in_long_range', 'super_damage_in_long_range'), ('super_damage_in_very_long_range', 'super_damage_in_very_long_range'), ('average_super_damage', 'average_super_damage'), ('ocasional_damage', 'ocasional_damage'), ('retreat_button', 'retreat_button'), ('wide_attack', 'wide_attack'), ('area_denial', 'area_denial'), ('enemy_position_manipulation', 'enemy_position_manipulation'), ('water_walking', 'water_walking'), ('counter_water_walking', 'counter_water_walking'), ('wall_break_efficiency', 'wall_break_efficiency'), ('grass_break_efficiency', 'grass_break_efficiency'), ('cover_creation_efficiency', 'cover_creation_efficiency'), ('grass_vision', 'grass_vision'), ('circumstantiality_of_overall_proficiency', 'circumstantiality_of_overall_proficiency'), ('heal_buffing', 'heal_buffing'), ('counter_heal_buffing', 'counter_heal_buffing'), ('shield_buffing', 'shield_buffing'), ('damage_buffing', 'damage_buffing'), ('counter_damage_buffing', 'counter_damage_buffing'), ('speed_buffing', 'speed_buffing'), ('invisibility_buffing', 'invisibility_buffing'), ('positioning_buffing', 'positioning_buffing'), ('poison_debuffing', 'poison_debuffing'), ('counter_poison_debuffing', 'counter_poison_debuffing'), ('stun_debuffing', 'stun_debuffing'), ('counter_stun_debuffing', 'counter_stun_debuffing'), ('slowness_debuffing', 'slowness_debuffing'), ('counter_slowness_debuffing', 'counter_slowness_debuffing'), ('block_enemies', 'block_enemies'), ('attacks_canceling', 'attacks_canceling'), ('counter_attacks_canceling', 'counter_attacks_canceling'), ('none', 'none')], default='none', help_text='Simple incapacity that could not be described until now', verbose_name='Specific Weakness'),
        ),
    ]
