# Generated by Django 6.0.2 on 2026-02-17 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proficiency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('base_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proficiency.proficiency', verbose_name='Base Proficiency')),
            ],
            options={
                'verbose_name': 'Gadget',
                'verbose_name_plural': 'Gadgets',
            },
        ),
        migrations.CreateModel(
            name='Hipercharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('base_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proficiency.proficiency', verbose_name='Base Proficiency')),
            ],
            options={
                'verbose_name': 'Hipercharge',
                'verbose_name_plural': 'Hipercharges',
            },
        ),
        migrations.CreateModel(
            name='StarPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('base_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proficiency.proficiency', verbose_name='Base Proficiency')),
            ],
            options={
                'verbose_name': 'Star Power',
                'verbose_name_plural': 'Star Powers',
            },
        ),
    ]
