# Generated by Django 6.0.2 on 2026-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_power', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='icon_name',
            field=models.CharField(default='unowngadget_icon.png', max_length=49, verbose_name='Gadget Icon Name'),
        ),
        migrations.AddField(
            model_name='hipercharge',
            name='icon_name',
            field=models.CharField(default='unownhipercharge_icon.png', max_length=49, verbose_name='Hypercharge Icon Name'),
        ),
        migrations.AddField(
            model_name='starpower',
            name='icon_name',
            field=models.CharField(default='unownstarpower_icon.png', max_length=49, verbose_name='Star Power Icon Name'),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Gadget Name'),
        ),
        migrations.AlterField(
            model_name='hipercharge',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Hipercharge Name'),
        ),
        migrations.AlterField(
            model_name='starpower',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Star Power Name'),
        ),
    ]
