# Generated by Django 6.0.2 on 2026-03-09 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_power', '0002_gadget_icon_name_hipercharge_icon_name_and_more'),
        ('proficiency', '0008_remove_proficiency_counter_durability_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='base_proficiency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proficiency.proficiency', verbose_name='Base Proficiency'),
        ),
        migrations.AlterField(
            model_name='hipercharge',
            name='base_proficiency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proficiency.proficiency', verbose_name='Base Proficiency'),
        ),
        migrations.AlterField(
            model_name='starpower',
            name='base_proficiency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proficiency.proficiency', verbose_name='Base Proficiency'),
        ),
    ]
