# Generated by Django 6.0.2 on 2026-06-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_power', '0003_alter_gadget_base_proficiency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gadget',
            old_name='name',
            new_name='additional_power_name',
        ),
        migrations.RenameField(
            model_name='hipercharge',
            old_name='name',
            new_name='additional_power_name',
        ),
        migrations.RenameField(
            model_name='starpower',
            old_name='name',
            new_name='additional_power_name',
        ),
    ]
